### ISSUE TITLE
[Request] Please add access to the phone contact list option

### ISSUE THREAD

**Issue by rodoviario** [apozas/contactdiary#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When you add a contact, be able to select an existing one from the phones contact app

**Describe alternatives you've considered**

**Additional context**

**Comment by apozas** [comment]
Hi. Thank you for the comment. This is currently being discussed in #3, so please make a comment in there. I'm proceeding to close this issue.
