### ISSUE TITLE
[Request] Dark mode

### ISSUE THREAD

**Issue by revuwa** [apozas/contactdiary#12]
My eyes would love to see a dark mode or black theme inside your great app.
This could save battery and preserve somebody's eyes from burning, especially in dark environments.

**Comment by apozas** [comment]
I totally agree, as I am the first one experiencing this. It will be added soon, although maybe not in the very next version.

**Comment by igor-cali** [comment]
@apozas I made some experiments to add the dark theme. One problem I encountered is that some layouts call for drawables with light colours .
At first glance, it is not clear to me what those light colours are for. If really necessary, this would lead to additional code.

E.g. `selector.xml` and `rounded_corner.xml`.

Thanks in advance for your hints.

**Comment by apozas** [comment]
No, thank you for giving it a shot :)

[selector.xml](https://github.com/apozas/contactdiary/blob/master/android_app/app/src/main/res/drawable/selector.xml) contains a call to `colorSelected` (in [colors.xml](https://github.com/apozas/contactdiary/blob/master/android_app/app/src/main/res/values/colors.xml)), that is the color of the background when in multiple selection mode. See the example below.
<img src="https://user-images.githubusercontent.com/25796774/97800317-97777e80-1c34-11eb-985e-87044626c655.png" width="300" height="200" />

[rounded_corner.xml](https://github.com/apozas/contactdiary/blob/master/android_app/app/src/main/res/drawable/rounded_corner.xml) defines the box behind the descriptions of the buttons after the FAB is uncollapsed. See the following figure
<img src="https://user-images.githubusercontent.com/25796774/97800519-220cad80-1c36-11eb-8b80-2c85bebdd252.png" width="400" height="200" />
I have realized that I can eliminate the `stroke` without consequences (and I'll do it in a subsequent commit), but `solid` is required (it is the color of the background) and ideally it would match the background color of the list.

Let me know if there's anything else you need to know.

**Comment by apozas** [comment]
How does this look?

<img src="https://user-images.githubusercontent.com/25796774/99591597-51ba0480-29ef-11eb-96e2-829c6eddd303.png" width="180" height="320" /> <img src="https://user-images.githubusercontent.com/25796774/99591686-731af080-29ef-11eb-9d40-e2ac44c75608.png" width="180" height="320" /> <img src="https://user-images.githubusercontent.com/25796774/99591700-7b732b80-29ef-11eb-9d3e-1dde9a050f8a.png" width="180" height="320" />

**Comment by GenosseFlosse** [comment]
Does this dark mode respect the system wide dark mode setting?

**Comment by apozas** [comment]
It is my intention that it does, although I am still struggling with it. While I know how to make it to follow it (it's a matter of setting in the appropriate place the flag `MODE_NIGHT_FOLLOW_SYSTEM`), I haven't figured out yet how to read _which_ is the system-wide choice. Right now, I need this in a few places.

Regarding the borders, this version has no borders between entries, only between days. I'm open to thoughts, so thanks for the feedback.

**Comment by apozas** [comment]
Having received no complaints (:stuck_out_tongue_closed_eyes:) one week after this version appeared on F-Droid, I'm closing this issue. Feel free to reopen if anything comes up.

**Comment by revuwa** [comment]
Even if late, I just wanted to thank you @apozas very much for the (fast and good looking) fulfillment of my wish ❤️
