### ISSUE TITLE
[Bug] "Show close contacts only" option not working; Contact list not changing by choosing this option

### ISSUE THREAD

**Issue by GenosseFlosse** [apozas/contactdiary#15]
**Description of the bug**
Choosing this option seems to have no effect on my shown contacts

**To Reproduce**
1. Go to Settings
2. Click on "show close contacts only" option
3. Go to contact list
4. See nothing changes

**Expected behavior**
List reduces at least by those contacts that I classified as "I kept the distance".

**Screenshots**
I won't screenshot my contact list here :/

**System information (please complete the following information):**
 - Device: POCOPHONE F1
 - Android version: 10
 - OS: MIUI 12.0.2
 - App version 1.1.4 (F-Droid)

**Comment by apozas** [comment]
Oh my. Thank you for noticing this. This originates in the infamous commit https://github.com/apozas/contactdiary/commit/efada112eabdbd697b1c0f94714942208580ce9b inserted in `v1.0.5`. Commit https://github.com/apozas/contactdiary/commit/20014021918759b53ae2ba6a4fa46ba7d3904c35 fixes it. Apologies for the hassle
