### ISSUE TITLE
[Bug] f-droid build failing

### ISSUE THREAD

**Issue by GenosseFlosse** [apozas/contactdiary#19]
**Description of the bug**
f-Droid build fails due to some issue I do not understand to describe: [f-droid wiki](https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_11)
Maybe there is sth. wrong with the updated dependencies?

**Expected behavior**
Flawless build

**Comment by eutektoid** [comment]
Well, I am not an expert and have close to nothing build experience with Android, but doesn't the [log](https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_11) say it went through with Gradle 6.1.1 and under `* What went wrong` says it would need minimum 6.5.?: 

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 6.5. Current version is 6.1.1. If using the gradle wrapper, try editing the distributionUrl in /home/vagrant/build/com.apozas.contactdiary/android_app/gradle/wrapper/gradle-wrapper.properties to gradle-6.5-all.zip
```

**Comment by GenosseFlosse** [comment]
Yeah. And my guess is that some of the updated dependencies in commit c3d817d require this minimum version.

**Comment by apozas** [comment]
https://github.com/apozas/contactdiary/commit/874d5ac4842c46da7669195985c84f0b242f1176 should fix this. Let's hope it is the case. Thanks for the notification.

**Comment by GenosseFlosse** [comment]
Yep, just updated my version! Again: Thank you a thousand times for your effort in developing this app!
