### ISSUE TITLE
[Bug] Import of CSV file not possible on different phone

### ISSUE THREAD

**Issue by LeicesterTriangle** [apozas/contactdiary#23]
Contact Diary version 1.3.0
Exported CSV file on old phone. Copied to file new phone (via PC), Samsung A51, Android 10, stock OS. Tried to import the file into a fresh install. 

ContactDiary.csv cannot be read, it remains greyed out in the choose file to import menu. 
It does not work on the SD card, or on the internal memory. 
Importing the file on the old phone works. 
Exporting a csv file on the new phone and trying to re-import it also fails.
Looking at the file on the PC: it looks just fine, strings separated by tabs, tab 0x0A at the end of the lines. 

I can manage -- I'll copy the data into a paper calendar:-) -- but this behaviour is unexpected.

**Comment by apozas** [comment]
Hi,

Thanks for letting me know. I'm sorry that you are having problems with this. It may have to do with the fact that I'm not explicitly asking for read/write permission, so it is possible that you can only import the database when it's on the `Downloads` folder (does this fix the issue). In any case, I'd like to ask you a bit more details on this statement:

> Exporting a csv file on the new phone and trying to re-import it also fails.

So, with your new phone, you have exported the file, and failed to import that same file? If true, this is a bit more worrying to me

**Comment by LeicesterTriangle** [comment]
On Wed, 09 Dec 2020 05:55:08 -0800, you wrote:

>Hi,
>
>Thanks for letting me know. I'm sorry that you are having problems with this. It may have to do with the fact that I'm not explicitly asking for read/write permission, so it is possible that you can only import the database when it's on the `Downloads` folder (does this fix the issue). In any case, I'd like to ask you a bit more details on this statement:

The files are in the folder "Download" -- tired both Sd-Card and internal
memory. (This is a Samsung, and it treats the SD-card a little differently than
internal memory.) 

The answer is "er, ah" !

I *think* I managed to re-import the file once. 

Right now, an export and re-import failed on the new phone. Should I reboot and
retry? (No, just did that, still no re-import.)

The app permissions don't allow file access, I saw that. I'm 98% sure it worked
at least once, though...


>> Exporting a csv file on the new phone and trying to re-import it also fails.
>
>So, with your new phone, you have exported the file, and failed to import that same file? If true, this is a bit more worrying to me

Yes. I hooked up the phone to a linux PC and tried a ls -al on the files, but
the permissions looked fine, i.e. identical to the locally saved file. chmod
failed, didn't work on the mounted SD card. 

I tried to append the contents of the file from the old phone to the new file
using command-line tools, using an editor, and using command-line tools.
"Operation not supported"... I gave up...


Thomas Prufer

**Comment by apozas** [comment]
Thanks for the work, really. I remembered I have an old Samsung with SD card. I'll try to reproduce the problem and get back to you.

**Comment by LeicesterTriangle** [comment]
On Wed, 09 Dec 2020 06:17:12 -0800, you wrote:

>Thanks for the work, really. I remembered I have an old Samsung with SD card. I'll try to reproduce the problem and get back to you.

Let me know what I can do to help. 

I'm in timezone Berlin/Amsterdam -- and I am fighting my new phone anyway:-)

**Comment by apozas** [comment]
In my Samsung phone I think I have at least partially reproduced your issue. When I export to the SD card, I cannot re-import. Also, I cannot import when I export to the SD card, move that file to the internal memory, and import from there. I can, however, import from the Downloads folder in the internal memory. Is this the behavior you are observing?

**Comment by LeicesterTriangle** [comment]
On Wed, 09 Dec 2020 09:30:37 -0800, you wrote:

>In my Samsung phone I think I have at least partially reproduced your issue. When I export to the SD card, I cannot re-import. Also, I cannot import when I export to the SD card, move that file to the internal memory, and import from there. I can, however, import from the Downloads folder in the internal memory. Is this the behavior you are observing?

It is very similar: I cannot reimport from the "Download" directory on the SD
card or from the internal memory. All files are greyed out. 

This doesn't look like a "Download" folder problem on my Samsung: I thought that
maybe the permissions of this folder are wrong, because the folder was or may
have been created by the "Smart Switch" app. (This is a Samsung app used to
migrate from an old phone to new.) A PDF downloaded by Firefox ends up in the
same directory as the ContactDiary.csv file...

**Comment by apozas** [comment]
I guess that any workarounds are nothing but workarounds, and the final solution requires to ask explicit read/write permission (which makes total sense). I will add this in the next version.

**Comment by LeicesterTriangle** [comment]
I tried the transfer the other way round, and can reproduce the behaviour: 

- Save csv on old phone. Re-importing that exact file works.
- Save csv on new phone, transfer to old phone (via PC). Import doesn't work,
file remains grayed out. 

So it's probably not Samsung-specific.

**Comment by apozas** [comment]
I can also reproduce something similar. In my non-Samsung phone, exporting the database somewehere, moving it somewhere else, and trying to import it back, fails. I think this has an easy fix (requesting the appropriate permissions), but I want to [do it right](https://developer.android.com/training/permissions/requesting). If all goes well, it will be done by the weekend.

**Comment by apozas** [comment]
In the end the solution seemed much simpler than anticipated. With https://github.com/apozas/contactdiary/commit/d650c3f3a744e2d50e8d8b5a8605f65f8f483c8e I am able to import a database that I generated in another phone, and that I am placing in a random folder in the SD card.

Now I am trying to handle an edge case, where the extension of the file transferred is not `.csv` (this is the case when you export the database putting the same filename than another file in the folder, so the extension turns into `.csv(1)`). I think this is very unlikely, but nevertheless I want to give it a shot. I know a simple solution, but I am working on something more elegant. In any case, if after the next update (coming in a couple of days) you still encounter problems, feel free to reopen.
