### ISSUE TITLE
Multiple choice values get filled in by app

### ISSUE THREAD

**Issue by ltGuillaume** [apozas/contactdiary#24]
**Description of the bug**
If you do not specify a value for the 3 multiple choice questions, the app will fill them in (`No`, `Outdoors` and `Not sure`, respectively). This will lead to confusion.

**To Reproduce**
1. Add new contact
2. Do not fill in the 3 multiple choice questions
4. Save and reopen the entry

**Expected behavior**
When reopening the entry, the multiple choice questions should remain empty.

**Comment by apozas** [comment]
Hi, I'm sorry that you are experiencing this. Unfortunately I am not being able to reproduce this on the latest version of the app, in Android 7, 8 or 9. Which app version and Android version are you using?

**Comment by ltGuillaume** [comment]
I'm using v1.3.1 from F-Droid. (I also needed to reinstall completely, because the app crashed every time after updating from 1.2 to 1.3, because of a SQL error that said there was a duplicate column "duration".)

**Comment by apozas** [comment]
Oh wow, I feel very bad for your experience. I am now reproducing the issue, so I will hopefully be able to fix it without too much of a problem. Fixing this is now the first priority.

**Comment by ltGuillaume** [comment]
Thanks! 🙂
