### ISSUE TITLE
Crowdin finished many languages

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [apozas/contactdiary#26]
on https://crowdin.com/project/contactdiary i finished:

dutch finished
french finished
german finished
finnish finished
hungarian finished
italian finished
polish finished
indonesian finished
swedish finished
portuguese finished
portuguese, brazilian finished

is my christmas present for you to put "under the christmas tree"

**Comment by apozas** [comment]
Wow, thanks a lot. And Merry Christmas to you too! :D
