### ISSUE TITLE
a treat for you, too

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [apozas/contactdiary#27]
i still have a treat for you before christmas. 
i promote free software by painting fdroid logos as acrylic paintings and promoting them on [mastodon ](https://mastodon.technology/@mondstern/105378509690147997) and [pixelfed](https://pixelfed.social/p/mondstern/244072952243556352). I hope you are happy.

**Comment by apozas** [comment]
That is very nice indeed! Thanks a lot, and Merry Christmas 😄 🎄
