### ISSUE TITLE
[Bug] "Make a copy today" doesn't work in 2021

### ISSUE THREAD

**Issue by Medath** [apozas/contactdiary#29]
**Description of the bug**
Long pressing a previous entry and tapping on "Make a copy today" creates an entry with the correct day and month, but the year seems to be hardcoded to 2020. Unfortunately it seems like covid still exists in 2021 :(

**To Reproduce**
1. Long press an entry from a previous day
2. Tap on "Make a copy today"
3. Scroll down to the bottom
4. See the entry being made for the wrong year

**Expected behavior**
The duplicated entry should be visible at the top with the correct year

**Screenshots**
None

**System information (please complete the following information):**
 - Device: OnePlus 3T
 - Android version: 8.1.0
 - OS: LineageOS with no Google Apps
 - App version: 1.3.2 from F-Droid

**Additional context**

**Comment by GenosseFlosse** [comment]
I experience the same behaviour on pocophone f1

**Comment by apozas** [comment]
I wonder why you noticed this only today :stuck_out_tongue_closed_eyes:. Thanks for the heads up. https://github.com/apozas/contactdiary/commit/9083927e264d5c2fb877b1e48c8d6bf8c12d2f66 should fix this. I'll release a new version straight away, so F-Droid can pick it up ASAP.

Happy New Year! :D
