### ISSUE TITLE
F-Droid Build Fails on versions 1.4.1 and 1.4.2

### ISSUE THREAD

**Issue by GenosseFlosse** [apozas/contactdiary#36]
```
* What went wrong:
Execution failed for task ':app:mergeGithubReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     /home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/layout/activity_addcontact_inside.xml:90: AAPT: error: duplicate attribute.
         
     /home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/layout/activity_addcontact_inside.xml: AAPT: error: file failed to compile.
```
https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_19
https://f-droid.org/wiki/page/com.apozas.contactdiary/lastbuild_17

Btw: there is a new app on F-Droid called "F-Droid Build Status" https://f-droid.org/en/packages/de.storchp.fdroidbuildstatus/
There you can receive notifications if a new build fails and directly have a look at the log.

**Comment by apozas** [comment]
Hi! Nice to see you around :)

Oh my. After more than a month without F-Droid picking up the updates, now this. It was my mistake, though, although I'm very surprised that this was not crashing my builds. I've made a [new release](https://github.com/apozas/contactdiary/releases/tag/v1.4.3) with the fixes and latest updates to the translations. Hopefully F-Droid will pick this one soon.

I knew about the app, but not that it would notify you of problems in the build. I'll definitely turn that on. Thanks!

**Comment by GenosseFlosse** [comment]
Yeah I noticed the troubles that F-Droid is having too. But it seems they got it fixed when everything is running smoothely now 👍 
I am closing this now and I look forward to my F-Droid updates in a few days :)
