### ISSUE TITLE
Cannot store a contact or event accross different dates

### ISSUE THREAD

**Issue by igor-cali** [apozas/contactdiary#37]
Use case: need to store contact event ending the day after the start. E.g. an event starting to 01/09/21 20 PM and ending on 02/09/21 2 AM.

Currently I can either end the event at 23:59 same day or store two different events.

I would like both the start and end dates to be shown in the main screen if they're different.

**Comment by apozas** [comment]
Hi! Long time no see :)

Thanks for the ides! I have stumbled upon this myself a few times, but I am not sure of what the best way of addressing it. I am a bit reluctant to modifying the current Contact/Event layout, although I'm open to be convinced otherwise. The logic that I have in mind right now is that the vast majority of events are not like the one you describe, so the current interface should change the slightest possible. Maybe a good solution is to add an "Add end date" button that will reveal the necessary fields if pressed. I'll play a bit with this idea in the following days. Thanks!

**Comment by igor-cali** [comment]
This is my simple design idea, for contacts and events:

![Schermata del 2021-08-16 00-22-07](https://user-images.githubusercontent.com/12466054/129494481-43517d89-2c01-49c9-8b03-b6ec6f2ee077.png).

I also removed duplicated inner xml layouts for edit_event and edit_contact, to harmonize them and optimize code and app size.
You can merge my pull request if you like the change proposal.

Cheers!

**Comment by apozas** [comment]
Thanks a lot for the code! It looks good, but I'm a bit time-limited this week. I believe that throughout the weekend I'll be able to merge the code. Thanks a lot!

**Comment by igor-cali** [comment]
> Thanks a lot for the code! It looks good, but I'm a bit time-limited this week. I believe that throughout the weekend I'll be able to merge the code. Thanks a lot!

OK, please keep in mind that I added two additional string resources, that will have to be translated.

**Comment by igor-cali** [comment]
@apozas I Think there's a issue on the translatins due to commits after the the merge of the PR.
As far as I an see the string "time", that I added, is not present anymore.
This prevents the build in F-Droid, as far as I understand.
See the [Build log for VersionCode 24](https://monitor.f-droid.org/builds/log/com.apozas.contactdiary/24):
> Task :app:lintVitalGithubRelease FAILED
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-es/strings.xml:10: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Hora</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-ca/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Hora</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-cs/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Čas</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-de/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Uhrzeit</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-fi/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Aika</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-fr/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Heure</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-hu/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Idő</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-id/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Waktu</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-ja/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">時刻</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-nl/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Tijdstip</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-pl/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Godzina</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-pt-rBR/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Hora</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-ru/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Время</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-sv/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Tid</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-tr/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Saat</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-uk/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">Час</string>
            ~~~~~~~~~~~
/home/vagrant/build/com.apozas.contactdiary/android_app/app/src/main/res/values-zh-rTW/strings.xml:11: Error: "time" is translated here but not found in default locale [ExtraTranslation]
    <string name="time">時間</string>
            ~~~~~~~~~~~
>    Explanation for issues of type "ExtraTranslation":
>    If a string appears in a specific language translation file, but there is
>    no corresponding string in the default locale, then this string is probably
>    unused. (It's technically possible that your application is only intended
>    to run in a specific locale, but it's still a good idea to provide a
>    fallback.)
> 
>    Note that these strings can lead to crashes if the string is looked up on
>    any locale not providing a translation, so it's important to clean them
>    up.
> 
> 17 errors, 0 warnings
> Lint found fatal errors while assembling a release target.

**Comment by apozas** [comment]
Thanks for the notice. I saw this a few days ago, and in fact later it was noticed in #39. Since it was not necessary after your contribution, I deleted the string `time` from the main `strings.xml` file, but not from the remaining, and that is what has caused the failure. The commit d57a5c02add986388f05c9fec3428649d8472999 removes the string from all localization files, and I am waiting for F-Droid to recompile. However, I have noticed that the app now appears in the [needs updating](https://monitor.f-droid.org/builds/needsupdate) list, and I don't know if this will be a problem. I thought of manually modifying [the app's metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.apozas.contactdiary.yml#L129) to see if this triggers the build. But any pointer on how to fix this is greatly appreciated.

11 sept. 2021 14:03:47 Igor ***@***.***>:

**Comment by igor-cali** [comment]
@apozas 

> I thought of manually modifying [the app's metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.apozas.contactdiary.yml#L129) to see if this triggers the build. But any pointer on how to fix this is greatly appreciated.

I think the easiest way to trigger the rebuild in F-Droid is to push a new release (I think you do this in this app by increasing the `VersionNumber` and `VersionCode` in the Manifest file.
Or, you can check with the repo maintainers.

**Comment by apozas** [comment]
Yes, that's probably the easiest one, but I would want to avoid it as much as possible, so as to have the notation consistent with the Play Store. I'll check with the repo maintainers, and see if something can be done from that side. If not, I'll just make a new version and release.
