### ISSUE TITLE
[Bug] Since version 1.4.7, the "make a copy today"-button is missing

### ISSUE THREAD

**Issue by dasnessie** [apozas/contactdiary#42]
**Description of the bug**
Since upgrading to version 1.4.7, the "make a copy today"-button (and the delete button) in the top right corner of the edit view are missing. It's easier to access than the menu entry (long vs short press), so I don't think it should be removed.

**To Reproduce**
1. Create a new entry
2. Click on it
3. See no buttons in the top right corner

**Expected behavior**
I expect to see two buttons in the top right corner, one for "make a copy today", and one for "delete".

**Screenshots**
<table>
  <tr>
    <th>
      <img src=https://user-images.githubusercontent.com/43586524/137022700-ae7ffb84-aeab-4956-9550-3c2581cdba33.png width='200px' title='Current behavior' />
    </th>
    <th>
      <img src=https://user-images.githubusercontent.com/43586524/137023114-f3e845de-2073-4bbf-93d2-e7bc3964edd6.png width='200px' title='expected, previous behavior' />
    </th>
  </tr>
</table>

**System information (please complete the following information):**
 - Device: Samsung Galaxy A5 (SM-A520F)
 - Android version: 9
 - OS: LineageOS 16.0
 - App version 1.4.7

**Additional context**
Feel free to ask for any other info you might need!

**Comment by apozas** [comment]
Thank you very much for noticing this. The removal was not intended, so I will fix it and release a new version soon (all things going well, before the end of the week).

**Comment by igor-cali** [comment]
I think this issue is originated with https://github.com/apozas/contactdiary/commit/f6ef1db8282fb21280eb63bdf104d6f71482823f.
I did not notice there where these buttons on the edit screens.

**Comment by apozas** [comment]
I believe that may be the case, indeed. I remember myself thinking on how to avoid using so many "same" layouts a few months ago, and there must had been a reason why my previous me didn't do it straight away xD. This is nevertheless a good excuse for me to find a more elegant solution. I will work on it today, and if I don't find an easy way I will just revert the changes. Thanks for your offering!

**Comment by igor-cali** [comment]
You can play with the `Visibility` attribute from tehbactivities to avoid multiple layouts.
