### ISSUE TITLE
To add Hindi translation of in-app text[Request]

### ISSUE THREAD

**Issue by PrathameshJadhav33** [apozas/contactdiary#46]
Hindi language is not listed currently in the language section so I would like to contribute by adding those translations on crowdin.

**Comment by apozas** [comment]
Hello @PrathameshJadhav33! Thank you very much for your willingness to contribute. I added the language now, you can access it [here](https://crowdin.com/project/contactdiary/hi). Thanks again, and don't hesitate letting me know if you encounter any more problems.

**Comment by apozas** [comment]
Well, there you go! https://github.com/apozas/contactdiary/commit/b32a292bf0259939b398036f98791ed819dad9d2. Thanks a lot!
